name: Docker_build_push

on:
  push:
    branches: [main, debug/**]
  pull_request:
  release:
    types: [created]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    uses: ./.github/workflows/docker_utils.yml
